pipeline: train_rl_finetune    # train_rl_finetune, test_rl_finetune, sample_rl_finetune
seed: 2025
device: cuda:1
data_config:
  pdb_data_dir: /cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/cfff_siqi/LatentDiffusion/DiffusionRL/example_data/rl_pdbs
  train_data_path: /cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/cfff_siqi/LatentDiffusion/DiffusionRL/example_data/rsda_valid_data.csv
  valid_data_path: /cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/cfff_siqi/LatentDiffusion/DiffusionRL/example_data/rsda_valid_data.csv
  test_data_path: /cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/cfff_siqi/LatentDiffusion/DiffusionRL/example_data/casp15_test_rl_diffusion.csv
  graph_featurizer:
    num_posenc: 16
    num_rbf: 16
    knn_num: 10
  latent_compressed:
    model_path: results/fixed_encoder_decoder/model_separate_epoch_49.pt
    encoder:
      name: mlp
      config:
        input_dim: 640
        hidden_dims:
        - 32
        dropout: 0.1

encoder_decoder_config:
  llm_config:
    name: 'rnafm'
    model_path: llm_ckpts/rnafm
    embed_channel: 640
  decoder:
    name: 'mlp'
    config:
      n_classes: 4
      encoder_hidden_dim: 32
      mlp_num_layers: 3
      mlp_dropout_p: 0.1
      add_sigmoid: False
  ckpt_path: 'results/fixed_encoder_decoder/model_separate_epoch_49.pt'

model_config:
  node_in_dim: [47, 4]   # latent_out_dim + 15
  node_h_dim: [512, 128]
  edge_in_dim: [32, 1]
  edge_h_dim: [128, 1]
  num_layers: 4
  drop_rate: 0.1
  dihedral_angle: True
  num_trans_layer: 8
  trans:
    encoder_embed_dim: 512
    encoder_attention_heads: 16
    attention_dropout: 0.1
    dropout: 0.1
    encoder_ffn_embed_dim: 1024
  latent_out_dim: 32

train_config:
  batch_size: 32
  lr: 0.00001
  wd: 0.001
  num_workers: 8
  output_dir: results/dpok_reward_curve/
  ckpt_path: results/fixed_latent_diffusion/model_epoch_45.pt
  max_train_epochs: 200
  gradient_accumulate_every: 32
  latent_transition_config:
    num_steps: 100

  rl_config:
    name: sold       #ddpo, dpok, sold
    recovery_weight: 0.0
    ss_weight: 0.0
    mfe_weight: 1.0
    lddt_weight: 0.0
    reward_weight: 1.0
    ref_kl_weight: 0.0
    pretrain_kl_weight: 0.01
    adv_clip_max: 5   # clip advantages to the range [-adv_clip_max, adv_clip_max]
    clip_range: 0.0001
    log_gradient_step: 30
    n_jobs: 16

  sampler: true  # sampler setting for train batch_size > 1
  sample_mode: time_batch
  max_squared_res: 150000
  train_dataset_mode: null     # add_noise or sample or leave_out or null
  loss_config:
    loss_seq:
      weight: 1.0
    loss_latent:
      weight: 1.0

test_config:
  ckpt_path: results/sold_exp/sold_mix_pretrain_kl_weight_0.0_recovery_0.0_ss_1.0_mfe_0.0_lddt_0.0/model_epoch_136.pt
  eval_single_step_metric:
    recovery: true
    ss: true
    mfe: true
    rmsd: false
    lddt: false